In [44]:
Group member: Yemin Wu;Yuxuan Zhang; Jingcheng Jiang;

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets
from ipywidgets import interact, interact_manual

In [45]:
import pandas as pd

ufos = pd.read_csv("/Users/zoe/Documents/590/ufo-scrubbed-geocoded-time-standardized-00.csv",
                  names = ["date", "city", "state", "country",
                          "shape", "duration_seconds", "duration",
                          "comment", "report_date", "latitude", "longitude"],
                  parse_dates = ["date", "report_date"])

First,I delete some NaN data which may afftect my plotting.

In [46]:
ufos = ufos.fillna({'country':'unknown', 'state':'unknown', 'shape':'unknown'})

In [48]:
ufos_col = ufos[["date", "city", "state", "country",
                          "shape", "duration_seconds", "duration",
                          "report_date", "latitude", "longitude"]]
ufos_col

,date,city,state,country,shape,duration_seconds,duration,report_date,latitude,longitude
0,1949-10-10 20:30:00,san marcos,tx,us,cylinder,2700.0,45 minutes,2004-04-27,29.883056,-97.941111
1,1949-10-10 21:00:00,lackland afb,tx,unknown,light,7200.0,1-2 hrs,2005-12-16,29.384210,-98.581082
2,1955-10-10 17:00:00,chester (uk/england),unknown,gb,circle,20.0,20 seconds,2008-01-21,53.200000,-2.916667
3,1956-10-10 21:00:00,edna,tx,us,circle,20.0,1/2 hour,2004-01-17,28.978333,-96.645833
4,1960-10-10 20:00:00,kaneohe,hi,us,light,900.0,15 minutes,2004-01-22,21.418056,-157.803611
5,1961-10-10 19:00:00,bristol,tn,us,sphere,300.0,5 minutes,2007-04-27,36.595000,-82.188889
6,1965-10-10 21:00:00,penarth (uk/wales),unknown,gb,circle,180.0,about 3 mins,2006-02-14,51.434722,-3.180000
7,1965-10-10 23:45:00,norwalk,ct,us,disk,1200.0,20 minutes,1999-10-02,41.117500,-73.408333
8,1966-10-10 20:00:00,pell city,al,us,disk,180.0,3 minutes,2009-03-19,33.586111,-86.286111
9,1966-10-10 21:00:00,live oak,fl,us,disk,120.0,several minutes,2005-05-11,30.294722,-82.984167
10,1968-10-10 13:00:00,hawthorne,ca,us,circle,300.0,5 min.,2003-10-31,33.916389,-118.351667
11,1968-10-10 19:00:00,brevard,nc,us,fireball,180.0,3 minutes,2008-06-12,35.233333,-82.734444
12,1970-10-10 16:00:00,bellmore,ny,us,disk,1800.0,30 min.,2000-05-11,40.668611,-73.527500
13,1970-10-10 19:00:00,manchester,ky,us,unknown,180.0,3 minutes,2008-02-14,37.153611,-83.761944
14,1971-10-10 21:00:00,lexington,nc,us,oval,30.0,30 seconds,2010-02-14,35.823889,-80.253611
15,1972-10-10 19:00:00,harlan county,ky,us,circle,1200.0,20minutes,2005-09-15,36.843056,-83.321944
16,1972-10-10 22:30:00,west bloomfield,mi,us,disk,120.0,2 minutes,2007-08-14,42.537778,-83.233056
17,1973-10-10 19:00:00,niantic,ct,us,disk,1800.0,20-30 min,2003-09-24,41.325278,-72.193611
18,1973-10-10 23:00:00,bermuda nas,unknown,unknown,light,20.0,20 sec.,2002-01-11,32.364167,-64.678611
19,1974-10-10 19:30:00,hudson,ma,us,other,2700.0,45 minutes,1999-08-10,42.391667,-71.566667
20,1974-10-10 21:30:00,cardiff (uk/wales),unknown,gb,disk,1200.0,20 minutes,2007-02-01,51.500000,-3.200000
21,1974-10-10 23:00:00,hudson,ks,us,light,1200.0,one hour?,2004-07-25,38.105556,-98.659722
22,1975-10-10 17:00:00,north charleston,sc,us,light,360.0,5-6 minutes,2008-02-14,32.854444,-79.975000
23,1976-10-10 20:30:00,washougal,wa,us,oval,60.0,1 minute,2014-02-07,45.582778,-122.352222
24,1976-10-10 22:00:00,stoke mandeville (uk/england),unknown,gb,cigar,3.0,3 seconds,2009-12-12,51.783333,-0.783333
25,1977-10-10 12:00:00,san antonio,tx,us,other,30.0,30 seconds,2005-02-24,29.423889,-98.493333
26,1977-10-10 22:00:00,louisville,ky,us,light,30.0,approx: 30 seconds,2004-03-17,38.254167,-85.759444
27,1978-10-10 02:00:00,elmont,ny,us,rectangle,300.0,5min,2007-02-01,40.700833,-73.713333
28,1979-10-10 00:00:00,poughkeepsie,ny,us,chevron,900.0,15 minutes,2005-04-16,41.700278,-73.921389
29,1979-10-10 22:00:00,saddle lake (canada),ab,unknown,triangle,270.0,4.5 or more min.,2005-01-19,53.970571,-111.689885
...,...,...,...,...,...,...,...,...,...,...
80302,2012-09-09 20:00:00,wilson,nc,us,light,10800.0,3 hours,2012-09-24,35.721111,-77.915833
80303,2012-09-09 20:10:00,elmont,ny,us,circle,600.0,10 minutes,2012-09-24,40.700833,-73.713333
80304,2012-09-09 20:30:00,mt. juliet,tn,us,light,120.0,2 minutes,2012-09-24,36.200000,-86.518611
80305,2012-09-09 20:30:00,ventura,ca,us,chevron,900.0,15 minutes,2012-09-24,34.278333,-119.292222
80306,2012-09-09 20:52:00,south jordan,ut,us,circle,10.0,10 seconds,2012-09-24,40.562222,-111.928889
80307,2012-09-09 21:00:00,elkhart,in,us,oval,600.0,10 minutes,2012-09-24,41.681944,-85.976667
80308,2012-09-09 21:00:00,new york city (brooklyn),ny,us,light,1290.0,21:30,2012-09-24,40.714167,-74.006389
80309,2012-09-09 21:00:00,pawleys island,sc,us,oval,60.0,less than a minute,2012-09-24,33.433056,-79.121667
80310,2012-09-09 21:00:00,ventura,ca,us,circle,300.0,5 minutes,2012-09-24,34.278333,-119.292222
80311,2012-09-09 21:55:00,charleston,sc,us,flash,900.0,15 minutes,2012-09-24,32.776389,-79.931111
80312,2012-09-09 23:00:00,gainesville,ga,us,light,5.0,5 seconds,2012-09-24,34.297778,-83.824167
80313,2013-09-09 00:15:00,norfolk,va,us,unknown,1.0,split second,2013-09-30,36.846667,-76.285556
80314,2013-09-09 01:50:00,buffalo (west of; on highway 90 west),ny,us,triangle,180.0,3 minutes,2013-09-30,42.886389,-78.878611
80315,2013-09-09 03:00:00,struthers,oh,us,unknown,120.0,2 minutes,2013-09-09,41.052500,-80.608056
80316,2013-09-09 09:51:00,san diego,ca,us,light,4.0,~4 seconds,2013-09-30,32.715278,-117.156389
80317,2013-09-09 12:34:00,cedar park,tx,us,cigar,8.0,5-8 seconds,2013-09-09,30.505000,-97.820000
80318,2013-09-09 13:10:00,calmar (canada),ab,ca,unknown,90.0,45-90 seconds,2013-09-09,53.250000,-113.783333
80319,2013-09-09 20:15:00,clifton,nj,unknown,other,3600.0,~1hr+,2013-09-30,40.858433,-74.163755
80320,2013-09-09 20:20:00,tuscaloosa,al,us,fireball,60.0,1:00,2013-09-30,33.209722,-87.569167
80321,2013-09-09 20:21:00,clarksville,tn,us,fireball,3.0,3 seconds,2013-09-30,36.529722,-87.359444
80322,2013-09-09 21:00:00,aleksandrow (poland),unknown,unknown,light,15.0,15 seconds,2013-09-30,50.465843,22.891814
80323,2013-09-09 21:00:00,gainesville,fl,us,triangle,60.0,1 minute,2013-09-30,29.651389,-82.325000
80324,2013-09-09 21:00:00,hamstead (hollyridge),nc,unknown,light,120.0,2 minutes,2013-09-30,34.367594,-77.710548
80325,2013-09-09 21:00:00,milton (canada),on,ca,fireball,180.0,3 minutes,2013-09-30,46.300000,-63.216667
80326,2013-09-09 21:00:00,woodstock,ga,us,sphere,20.0,20 seconds,2013-09-30,34.101389,-84.519444
80327,2013-09-09 21:15:00,nashville,tn,us,light,600.0,10 minutes,2013-09-30,36.165833,-86.784444
80328,2013-09-09 22:00:00,boise,id,us,circle,1200.0,20 minutes,2013-09-30,43.613611,-116.202500
80329,2013-09-09 22:00:00,napa,ca,us,other,1200.0,hour,2013-09-30,38.297222,-122.284444
80330,2013-09-09 22:20:00,vienna,va,us,circle,5.0,5 seconds,2013-09-30,38.901111,-77.265556
80331,2013-09-09 23:00:00,edmond,ok,us,cigar,1020.0,17 minutes,2013-09-30,35.652778,-97.477778

 "comment" is neither a numercial variable nor a categorial variable so i delete this column here.

In [49]:
del ufos["comment"]

### Question 1

Do you want the user to be able to pick any 2 columns?  Or only certain columns?  Why or why not?


I do not want the user to be able to pick any 2 columns because some columns do not make sense together such as state and city. So I separete numerical and categorical variables. I first select ufos_numerical which are numerical variables because I want to use these as my colormap.I use ipywidgets to make my plot become interactive.

In [50]:
ufos_numerical = ufos[["duration_seconds", "latitude", "longitude"]]
ufos_numerical

       duration_seconds   latitude   longitude
0                2700.0  29.883056  -97.941111
1                7200.0  29.384210  -98.581082
2                  20.0  53.200000   -2.916667
3                  20.0  28.978333  -96.645833
4                 900.0  21.418056 -157.803611
5                 300.0  36.595000  -82.188889
6                 180.0  51.434722   -3.180000
7                1200.0  41.117500  -73.408333
8                 180.0  33.586111  -86.286111
9                 120.0  30.294722  -82.984167
10                300.0  33.916389 -118.351667
11                180.0  35.233333  -82.734444
12               1800.0  40.668611  -73.527500
13                180.0  37.153611  -83.761944
14                 30.0  35.823889  -80.253611
15               1200.0  36.843056  -83.321944
16                120.0  42.537778  -83.233056
17               1800.0  41.325278  -72.193611
18                 20.0  32.364167  -64.678611
19               2700.0  42.391667  -71.566667
20               1200.0  51.500000   -3.200000
21               1200.0  38.105556  -98.659722
22                360.0  32.854444  -79.975000
23                 60.0  45.582778 -122.352222
24                  3.0  51.783333   -0.783333
25                 30.0  29.423889  -98.493333
26                 30.0  38.254167  -85.759444
27                300.0  40.700833  -73.713333
28                900.0  41.700278  -73.921389
29                270.0  53.970571 -111.689885
...                 ...        ...         ...
80302           10800.0  35.721111  -77.915833
80303             600.0  40.700833  -73.713333
80304             120.0  36.200000  -86.518611
80305             900.0  34.278333 -119.292222
80306              10.0  40.562222 -111.928889
80307             600.0  41.681944  -85.976667
80308            1290.0  40.714167  -74.006389
80309              60.0  33.433056  -79.121667
80310             300.0  34.278333 -119.292222
80311             900.0  32.776389  -79.931111
80312               5.0  34.297778  -83.824167
80313               1.0  36.846667  -76.285556
80314             180.0  42.886389  -78.878611
80315             120.0  41.052500  -80.608056
80316               4.0  32.715278 -117.156389
80317               8.0  30.505000  -97.820000
80318              90.0  53.250000 -113.783333
80319            3600.0  40.858433  -74.163755
80320              60.0  33.209722  -87.569167
80321               3.0  36.529722  -87.359444
80322              15.0  50.465843   22.891814
80323              60.0  29.651389  -82.325000
80324             120.0  34.367594  -77.710548
80325             180.0  46.300000  -63.216667
80326              20.0  34.101389  -84.519444
80327             600.0  36.165833  -86.784444
80328            1200.0  43.613611 -116.202500
80329            1200.0  38.297222 -122.284444
80330               5.0  38.901111  -77.265556
80331            1020.0  35.652778  -97.477778

[80332 rows x 3 columns]

In [51]:
@ipywidgets.interact(col_name1 = ufos_col.columns, col_name2 = ufos_col.columns, colormap = ufos_numerical.columns)
def create_plot(col_name1, col_name2, colormap):
    fig,ax = plt.subplots(figsize=(10,6))
    ax.scatter(ufos[col_name1], ufos[col_name2], c=np.log10(ufos[colormap]))
    ax.set_xlabel(col_name1)
    ax.set_ylabel(col_name2)
    plt.show()

interactive(children=(Dropdown(description='col_name1', options=('date', 'city', 'state', 'country', 'shape', …

### Question 2

As for question 2, I first select categorical variables. I use @ipywidgets.interact(column = ufos_categorical.columns, bins = bins_itext) to achieve the interactive function here.

In [52]:
ufos_categorical = ufos[["date", "city", "state", "country", "shape", "report_date"]]
ufos_categorical

,date,city,state,country,shape,report_date
0,1949-10-10 20:30:00,san marcos,tx,us,cylinder,2004-04-27
1,1949-10-10 21:00:00,lackland afb,tx,unknown,light,2005-12-16
2,1955-10-10 17:00:00,chester (uk/england),unknown,gb,circle,2008-01-21
3,1956-10-10 21:00:00,edna,tx,us,circle,2004-01-17
4,1960-10-10 20:00:00,kaneohe,hi,us,light,2004-01-22
5,1961-10-10 19:00:00,bristol,tn,us,sphere,2007-04-27
6,1965-10-10 21:00:00,penarth (uk/wales),unknown,gb,circle,2006-02-14
7,1965-10-10 23:45:00,norwalk,ct,us,disk,1999-10-02
8,1966-10-10 20:00:00,pell city,al,us,disk,2009-03-19
9,1966-10-10 21:00:00,live oak,fl,us,disk,2005-05-11
10,1968-10-10 13:00:00,hawthorne,ca,us,circle,2003-10-31
11,1968-10-10 19:00:00,brevard,nc,us,fireball,2008-06-12
12,1970-10-10 16:00:00,bellmore,ny,us,disk,2000-05-11
13,1970-10-10 19:00:00,manchester,ky,us,unknown,2008-02-14
14,1971-10-10 21:00:00,lexington,nc,us,oval,2010-02-14
15,1972-10-10 19:00:00,harlan county,ky,us,circle,2005-09-15
16,1972-10-10 22:30:00,west bloomfield,mi,us,disk,2007-08-14
17,1973-10-10 19:00:00,niantic,ct,us,disk,2003-09-24
18,1973-10-10 23:00:00,bermuda nas,unknown,unknown,light,2002-01-11
19,1974-10-10 19:30:00,hudson,ma,us,other,1999-08-10
20,1974-10-10 21:30:00,cardiff (uk/wales),unknown,gb,disk,2007-02-01
21,1974-10-10 23:00:00,hudson,ks,us,light,2004-07-25
22,1975-10-10 17:00:00,north charleston,sc,us,light,2008-02-14
23,1976-10-10 20:30:00,washougal,wa,us,oval,2014-02-07
24,1976-10-10 22:00:00,stoke mandeville (uk/england),unknown,gb,cigar,2009-12-12
25,1977-10-10 12:00:00,san antonio,tx,us,other,2005-02-24
26,1977-10-10 22:00:00,louisville,ky,us,light,2004-03-17
27,1978-10-10 02:00:00,elmont,ny,us,rectangle,2007-02-01
28,1979-10-10 00:00:00,poughkeepsie,ny,us,chevron,2005-04-16
29,1979-10-10 22:00:00,saddle lake (canada),ab,unknown,triangle,2005-01-19
...,...,...,...,...,...,...
80302,2012-09-09 20:00:00,wilson,nc,us,light,2012-09-24
80303,2012-09-09 20:10:00,elmont,ny,us,circle,2012-09-24
80304,2012-09-09 20:30:00,mt. juliet,tn,us,light,2012-09-24
80305,2012-09-09 20:30:00,ventura,ca,us,chevron,2012-09-24
80306,2012-09-09 20:52:00,south jordan,ut,us,circle,2012-09-24
80307,2012-09-09 21:00:00,elkhart,in,us,oval,2012-09-24
80308,2012-09-09 21:00:00,new york city (brooklyn),ny,us,light,2012-09-24
80309,2012-09-09 21:00:00,pawleys island,sc,us,oval,2012-09-24
80310,2012-09-09 21:00:00,ventura,ca,us,circle,2012-09-24
80311,2012-09-09 21:55:00,charleston,sc,us,flash,2012-09-24
80312,2012-09-09 23:00:00,gainesville,ga,us,light,2012-09-24
80313,2013-09-09 00:15:00,norfolk,va,us,unknown,2013-09-30
80314,2013-09-09 01:50:00,buffalo (west of; on highway 90 west),ny,us,triangle,2013-09-30
80315,2013-09-09 03:00:00,struthers,oh,us,unknown,2013-09-09
80316,2013-09-09 09:51:00,san diego,ca,us,light,2013-09-30
80317,2013-09-09 12:34:00,cedar park,tx,us,cigar,2013-09-09
80318,2013-09-09 13:10:00,calmar (canada),ab,ca,unknown,2013-09-09
80319,2013-09-09 20:15:00,clifton,nj,unknown,other,2013-09-30
80320,2013-09-09 20:20:00,tuscaloosa,al,us,fireball,2013-09-30
80321,2013-09-09 20:21:00,clarksville,tn,us,fireball,2013-09-30
80322,2013-09-09 21:00:00,aleksandrow (poland),unknown,unknown,light,2013-09-30
80323,2013-09-09 21:00:00,gainesville,fl,us,triangle,2013-09-30
80324,2013-09-09 21:00:00,hamstead (hollyridge),nc,unknown,light,2013-09-30
80325,2013-09-09 21:00:00,milton (canada),on,ca,fireball,2013-09-30
80326,2013-09-09 21:00:00,woodstock,ga,us,sphere,2013-09-30
80327,2013-09-09 21:15:00,nashville,tn,us,light,2013-09-30
80328,2013-09-09 22:00:00,boise,id,us,circle,2013-09-30
80329,2013-09-09 22:00:00,napa,ca,us,other,2013-09-30
80330,2013-09-09 22:20:00,vienna,va,us,circle,2013-09-30
80331,2013-09-09 23:00:00,edmond,ok,us,cigar,2013-09-30

In [54]:
bins_itext = ipywidgets.IntText()
bins_itext.value = 20
@ipywidgets.interact(column = ufos_categorical.columns, bins = bins_itext)
def creat_hist(column, bins):
    fig,ax = plt.subplots(figsize=(8,6))
    ax.hist(x = ufos[column], bins = bins)
    ax.set_xlabel(column)
    plt.show()

interactive(children=(Dropdown(description='column', options=('date', 'city', 'state', 'country', 'shape', 're…